In [2]:
import torch
import torch.nn as nn

In [4]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()

                            # input, output
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    output = self.linear(features)
    output = self.sigmoid(output)

    return output

In [6]:
features = torch.rand(10, 5)
features

tensor([[0.0203, 0.0067, 0.5449, 0.0115, 0.0012],
        [0.9766, 0.7379, 0.3668, 0.1049, 0.6385],
        [0.5109, 0.1949, 0.5783, 0.0149, 0.9891],
        [0.6863, 0.9685, 0.7326, 0.4541, 0.3107],
        [0.1210, 0.3480, 0.9056, 0.4078, 0.5578],
        [0.3824, 0.9536, 0.5222, 0.1203, 0.5763],
        [0.3859, 0.8991, 0.4825, 0.2629, 0.2733],
        [0.9376, 0.5100, 0.0116, 0.0736, 0.7106],
        [0.9062, 0.6473, 0.4625, 0.3292, 0.6318],
        [0.7019, 0.6442, 0.3170, 0.2865, 0.3858]])

In [8]:
features.shape

torch.Size([10, 5])

In [10]:
model = Model(features.shape[1])
model

Model(
  (linear): Linear(in_features=5, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [12]:
# model.forward(features)
model(features)

tensor([[0.5404],
        [0.4570],
        [0.4292],
        [0.4986],
        [0.4830],
        [0.4860],
        [0.5145],
        [0.4504],
        [0.4568],
        [0.4893]], grad_fn=<SigmoidBackward0>)

In [13]:
model.linear.weight

Parameter containing:
tensor([[-0.1399,  0.0644, -0.0293, -0.0203, -0.3945]], requires_grad=True)

In [14]:
!pip install torchinfo

In [15]:
from torchinfo import summary

summary(model, input_size=features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Multiple layer usage

In [16]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.network = nn.Sequential(
      nn.Linear(num_features, 3),
      nn.ReLU(),
      nn.Linear(3, 1),
      nn.Sigmoid()
    )

  def forward(self, features):
    output = self.network(features)

    return output

In [17]:
features = torch.rand(10, 5)
features

tensor([[7.8078e-01, 8.4372e-01, 3.3686e-01, 4.2750e-01, 4.3125e-01],
        [6.1802e-01, 8.3477e-01, 8.4866e-01, 5.9925e-01, 3.5191e-04],
        [8.1202e-01, 6.2885e-01, 3.0561e-01, 4.9774e-01, 1.1351e-01],
        [3.3590e-01, 2.8979e-01, 8.0827e-01, 5.3802e-01, 4.9466e-01],
        [7.3919e-01, 2.5229e-01, 6.2367e-01, 3.9583e-01, 5.4449e-01],
        [6.1343e-01, 1.7605e-01, 5.3793e-04, 3.6172e-01, 7.0703e-01],
        [5.2257e-01, 2.4696e-01, 5.5571e-01, 8.3275e-01, 8.5491e-01],
        [2.6460e-01, 2.4766e-01, 2.6933e-01, 4.3039e-01, 2.3227e-01],
        [5.2844e-01, 5.9204e-01, 4.6601e-01, 1.7730e-01, 1.5100e-01],
        [9.2067e-01, 5.4982e-01, 5.9846e-02, 4.3384e-01, 3.5090e-01]])

In [19]:
model = Model(features.shape[1])
model

Model(
  (network): Sequential(
    (0): Linear(in_features=5, out_features=3, bias=True)
    (1): ReLU()
    (2): Linear(in_features=3, out_features=1, bias=True)
    (3): Sigmoid()
  )
)

In [20]:
# model.forward(features)
model(features)

tensor([[0.6630],
        [0.6390],
        [0.6514],
        [0.6207],
        [0.6352],
        [0.6465],
        [0.6500],
        [0.6203],
        [0.6275],
        [0.6623]], grad_fn=<SigmoidBackward0>)

In [25]:
model.network[0].weight

Parameter containing:
tensor([[-0.3822, -0.3831, -0.1860,  0.0033, -0.3438],
        [ 0.0172, -0.3847, -0.1333, -0.3355, -0.3404],
        [ 0.4207,  0.4377, -0.2974,  0.3628,  0.3034]], requires_grad=True)

In [26]:
summary(model, input_size=features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00