In [1]:
def fun():
    print("Hello World!")

fun()

Hello World!


In [2]:
def addition(a, b):
    return a + b

print(addition(10, 30))

40


In [3]:
# default value 
def addition(a, b, c=10):
    return a + b + c


sum1 = addition(10, 25)
print(sum1)

# pass perameter keyword
sum2 = addition(c=20, a=8, b=5)
print(sum2)

45
33


In [4]:
# args

def squires_multiple(*args):
    print(args) # return tuple
    print(*args)
    mul = 1
    for x in args:
        mul *= x**2
    return mul

mul = squires_multiple(1, 2, 5, 6)
print(mul)


(1, 2, 5, 6)
1 2 5 6
3600


In [5]:
# kwargs
def display(**kwargs):
    print(kwargs) # return tuple
    name = kwargs.get("name")
    print("name :", name)
    for k,v in kwargs.items():
        print(f"{k} : {v}")
    

display(name="saimun", roll="15", address="Dhaka")



{'name': 'saimun', 'roll': '15', 'address': 'Dhaka'}
name : saimun
name : saimun
roll : 15
address : Dhaka


In [6]:
def get_data():
    a = [1, 2, 5]
    return a, "successfully retrived"

data = get_data()
print(data)
data, message = get_data()
print(data, message)

([1, 2, 5], 'successfully retrived')
[1, 2, 5] successfully retrived


In [7]:
def get_data():
    a = [1, 2, 5]
    b = {'a', 'b', 'c'}
    return a, b

lst, st = get_data()
print(type(lst), type(st))
print(lst, st)


<class 'list'> <class 'set'>
[1, 2, 5] {'a', 'b', 'c'}


In [8]:
st = {10, 20, 50, 60}

st_iter = iter(st)
print(type(st_iter))
print(next(st_iter))
print(next(st_iter))
print(next(st_iter))


lst = [1, 5, 6, 7]

<class 'set_iterator'>
10
20
50


In [9]:
## Generator

In [10]:
data = [i for i in range(100)]
print(data)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [11]:
def chunk_data(lst, size):
    for i in range(0, len(lst), size):
        yield lst[i : i + size]

lst = chunk_data(data, 10)
print(lst)
print(type(lst))

d1 = next(lst)
print(d1)
print(next(lst))
print(next(lst))
print(next(lst))
print(next(lst))


<generator object chunk_data at 0x10a0b4c70>
<class 'generator'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
[30, 31, 32, 33, 34, 35, 36, 37, 38, 39]
[40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


In [12]:
# syntax: lambda perameters: expression

square = lambda x : x**2
print(square(5))

square_add = lambda *args : sum([x**2 for x in args])

print(square_add(1, 2, 5, 6))

25
66


In [13]:
# syntax: map(fucntion: iterable) **iterable like list, set, string etc
lst = [1, 2, 3, 4, 5, 6]

def sq(a):
    return a**2
    
new_lst = list(map(sq, lst))
print(new_lst)


[1, 4, 9, 16, 25, 36]


### Map X Lambda

In [14]:
lst = [1, 2, 3, 4, 5, 6]
 
new_lst = list(map(lambda x : x**2, lst))
print(new_lst)

st = "Hello World, Phitron"

new_st = list(map(str.upper, st))
new_st = "".join(new_st)
print(new_st)

[1, 4, 9, 16, 25, 36]
HELLO WORLD, PHITRON


In [15]:
lst = [1, 2, 3, 4, 5, 6]
 
new_lst = list(map(lambda x : x**2 if x%2 else x, lst))
print(new_lst)


[1, 2, 9, 4, 25, 6]


In [16]:
# syntax: filter(function that return boolean : iterable)
lst = [i for i in range(100)]

def is_even(x):
    return x % 2 == 0

new_lst = list(filter(is_even, lst))
print(new_lst)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [17]:
new_lst = list(filter(lambda x : x % 2, lst))
print(new_lst)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]


In [18]:
lst = ['a', None, True, 1, 2, False, None]

new_lst = list(filter(None, lst))
print(new_lst)

st = "Hello world, Everybody"
print(list(filter(lambda c: c.lower() in "aeiou", st)))

['a', True, 1, 2]
['e', 'o', 'o', 'E', 'e', 'o']


## why use numpy array over python list

#### Task is print array elemnt multiply by 5

In [19]:
# using python list

arr = [1,2,3]

print( arr * 5 )

arr = [ x*5 for x in arr] 

print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [20]:
import numpy as np
# only use same type of data
arr = np.array([1, 2, 3, 4])

arr = arr * 5 # use SIMD single instruction multiple data

print(arr)

[ 5 10 15 20]


## NDArray

In [21]:
# import numpy as np 

# 1d array 
arr1 = np.array([1, 2, 3, 4])

# 2d array
arr2 = np.array([
        [1, 2, 3],
        [4, 5, 6]
])
    

# 3d array
arr3 = np.array([
    [ [1, 2, 3],
      [4, 5, 6] ],
    
    [ [1, 2, 3],
      [4, 5, 6] ],

    [ [1, 2, 3],
      [4, 5, 6] ],
])
print("=== 1d ====")
print(arr1)
print("\n=== 2d ====\n")
print(arr2)
print("\n=== 3d ====\n")
print(arr3)

=== 1d ====
[1 2 3 4]

=== 2d ====

[[1 2 3]
 [4 5 6]]

=== 3d ====

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Array attributes

In [22]:
# dimantion of array
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

# array shape
# (4,)
# (2, 3) # row, col
# (3, 2, 3) # flor, row, col
print(arr1.shape)
print(arr2.shape)
print(arr3.shape) 

# array size
print(arr1.size)
print(arr2.size)
print(arr3.size)

# array datatyp

print(arr3.dtype)


1
2
3
(4,)
(2, 3)
(3, 2, 3)
4
6
18
int64


## ndarray data type

In [23]:
arr1 = np.array([1, 2, 3, 5])

print(arr1.dtype)

arr2 = np.array([1.2, 2.6, 8.4, 5.00])
print(arr2.dtype)

int64
float64


In [24]:
arr = np.array([1, 2, 3, 5.2])

# upcasting to float 
print(arr.dtype)

# upcasting to string
arr = np.array([1, 2, 3, 5.2, 'hello'])
print(arr.dtype)

arr = np.array([1,True, 0])
print(arr.dtype, arr)

float64
<U32
int64 [1 1 0]


## selecting a data type for an array

In [25]:
arr = np.array([1, 2, 3, 5.2], dtype=np.int8)
print(arr.dtype)
print(arr)

arr = arr.astype(np.float64)
print(arr.dtype)
print(arr)

# error
arr = np.array([1, 2, 3, 5.2, "helo"], dtype=np.int8)

int8
[1 2 3 5]
float64
[1. 2. 3. 5.]


ValueError: invalid literal for int() with base 10: 'helo'

## ndarray creation from existing data

In [ ]:
# list

arr = [1, 2, 3]
arr = np.array(arr)
print(arr.dtype)
print(type(arr))
print(arr)


arr = [1, 2, 3, 'sk']
arr = np.array(arr)
print(arr.dtype)
print(type(arr))
print(arr)

In [ ]:
# tuple

arr = (1, 2, 3)
arr = np.array(arr)
print(arr.dtype)
print(arr.ndim)
print(type(arr))
print(arr)

In [ ]:
# set

arr = {1, 2, 3}
arr = np.array(arr)
print(arr.dtype)
print(arr.ndim)
print(type(arr))
print(arr)



arr = {1, 2, 3}
arr = np.array(list(arr))
print(arr.dtype)
print(arr.ndim)
print(type(arr))
print(arr)

In [ ]:
# dict

dic = {'a': 1, 'b': 2, 'c': 3}
arr = np.array(dic)
print(arr.dtype)
print(arr.ndim)
print(type(arr))
print(arr)

keys = dic.keys()
items = dic.items()
values = dic.values()

print(keys)
print(values)
print(items)


In [ ]:
# dict keys

arr = np.array(keys)
print(arr.dtype)
print(arr.ndim)
print(type(arr))
print(arr)

# convert list
arr = np.array(list(keys))
print(arr.dtype)
print(arr.ndim)
print(type(arr))
print(arr)

In [ ]:
# dict values

arr = np.array(values)
print(arr.dtype)
print(arr.ndim)
print(type(arr))
print(arr)


# convert list

arr = np.array(list(values))
print(arr.dtype)
print(arr.ndim)
print(type(arr))
print(arr)



In [ ]:
# dict items

arr = np.array(items)
print(arr.dtype)
print(arr.ndim)
print(type(arr))
print(arr)


# convert list

arr = np.array(list(items))
print(arr.dtype)
print(arr.ndim)
print(type(arr))
print(arr.shape)
print(arr.size)
print(arr)


## Creating ndarray from scratch

In [ ]:
# empty array with zero

arr = np.zeros((1, 5)) # defalut float we can change
arr = np.zeros((1, 5), dtype=np.int64) # defalut float we can change
# arr = np.zeros(5)
print(arr.dtype)
print(arr.ndim)
print(type(arr))
print(arr.shape)
print(arr.size)
print(arr)


# 2d
arr = np.zeros((2, 5), dtype=np.int64) # defalut float we can change

print(arr.dtype)
print(arr.ndim)
print(type(arr))
print(arr.shape)
print(arr.size)
print(arr)


# 3d
arr = np.zeros((3, 5), dtype=np.int64) # defalut float we can change

print(arr.dtype)
print(arr.ndim)
print(type(arr))
print(arr.shape)
print(arr.size)
print(arr)

# use shape of another array
arr = np.zeros_like(arr3) ## arr3 shape same 
print(arr)
print(arr.shape) 

In [ ]:
# empty array with one

arr = np.ones((1, 5)) # defalut float we can change
arr = np.ones((1, 5), dtype=np.int64) # defalut float we can change
# arr = np.zeros(5)
print(arr.dtype)
print(arr.ndim)
print(type(arr))
print(arr.shape)
print(arr.size)
print(arr)


# 2d
arr = np.ones((2, 5), dtype=np.int64) # defalut float we can change

print(arr.dtype)
print(arr.ndim)
print(type(arr))
print(arr.shape)
print(arr.size)
print(arr)


# 3d
arr = np.ones((3, 5), dtype=np.int64) # defalut float we can change

print(arr.dtype)
print(arr.ndim)
print(type(arr))
print(arr.shape)
print(arr.size)
print(arr)

# use shape of another array
arr = np.ones_like(arr3) ## arr3 shape same 
print(arr)
print(arr.shape) 

In [ ]:
# empty array with input value

arr = np.full((1, 5), 99) # defalut float we can change
arr = np.full((1, 5), 99, dtype=np.int64) # defalut float we can change
# arr = np.zeros(5)
print(arr.dtype)
print(arr.ndim)
print(type(arr))
print(arr.shape)
print(arr.size)
print(arr)


# 2d
arr = np.full((2, 5), 99, dtype=np.int64) # defalut float we can change

print(arr.dtype)
print(arr.ndim)
print(type(arr))
print(arr.shape)
print(arr.size)
print(arr)


# 3d
arr = np.full((3, 5), 99, dtype=np.int64) # defalut float we can change

print(arr.dtype)
print(arr.ndim)
print(type(arr))
print(arr.shape)
print(arr.size)
print(arr)

# use shape of another array
arr = np.full_like(arr3, 10) ## arr3 shape same 
print(arr)
print(arr.shape) 

# empty array with inpinite

In [ ]:
arr = np.full_like(arr3, np.inf) ## bydefault it use int64
print(arr)
print(arr.shape)
print(arr.dtype)


arr = np.full_like(arr3, np.inf, dtype=np.float64) ## bydefault it use int64
print(arr)
print(arr.shape)
print(arr.dtype)


In [ ]:
#np.empty
arr = np.empty((4,3),dtype=np.int8)

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

arr = np.empty_like(arr3) ## arr3 shape same 
print(arr)
print(arr.shape) 

## array creation with random values

In [ ]:
# np.random.rand(shape) 

arr = np.random.rand(2,3) # 0 ->1 

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

In [ ]:
# np.random.randint(start, end, shape) 

arr = np.random.randint(1,5 , (2,3))  

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

In [ ]:
# np.random.uniform(start, end, shape) 

arr = np.random.uniform(1,500 , (2,3))  # floating number

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

## array creation with range functions

In [ ]:
# np.arange(first , end , step ) -> similar to range function 

arr = np.arange(1 , 10 ,1 )
mat = arr.reshape(3,3) 

print(arr) 
print(mat) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)



[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [ ]:
# np.linspace(first , end(included) , size ) -> in array linearly all element deffrence is same

arr = np.linspace(1 , 10 , 9 )

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]
<class 'numpy.ndarray'>
float64
(9,)
1
9


In [ ]:
# np.logspace(start , end, size, base=10 ) -> base ^ start .. . .. . base ^ end 

arr = np.logspace(0, 10 , 6 , dtype=np.int64)

print(arr) 

arr = np.logspace(0, 10 , 6 , base=2, dtype=np.int64)
print(arr) 

arr = np.logspace(0, 9 , 6 , base=2, dtype=np.int64)
print(arr)

[          1         100       10000     1000000   100000000 10000000000]
[   1    4   16   64  256 1024]
[  1   3  12  42 147 512]


## Matrix

In [ ]:
# diagonal matrix

arr = np.diag([1, 3, 4, 5])
print(arr)

[[1 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [ ]:
# identity matrix

arr = np.identity(3, dtype=np.int8)

print(arr)
print(arr.shape)

# 4 X 4 size identity matrix
arr = np.eye(4, 4)
print(arr)

# np.eye(row, col, k)
# if k is positive then diagonal goes to upper else reversed
arr = np.eye(5, 5, 2)
print(arr)
print("\n==== senaro 3=====\n")
arr = np.eye(5, 5, -1)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
(3, 3)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

==== senaro 3=====

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


## ndarray indexing

In [ ]:
# 1d array 
arr1 = np.array([1, 2, 3, 4])

# 2d array
arr2 = np.array([
        [1, 2, 3],
        [4, 5, 6]
])


In [ ]:
# 1d array
print(arr1[0])

arr1[2] = 100
print(arr1)


1
[  1   2 100   4]


In [ ]:

# 2d array

# get full row 
print(arr2[0])

print(arr2[1])

print(arr2[1][2])

[1 2 3]
[4 5 6]
6


## Slicing

In [ ]:
# 1d array

#arr = arr1[start: end(not included): step]
print(arr1)
print(arr1[::-1]) # reverse

print(arr1[0::2])


[  1   2 100   4]
[  4 100   2   1]
[  1 100]


In [ ]:
# 2d array

#arr = arr1[row_start : row_end: step, col_start : col_end : step]

arr = np.arange(1 , 10 ,1 )
mat = arr.reshape(3,3) 
print(mat)
print("\n == Row == \n")


## ================== ROW ============== 
# get first row
print(mat[0:1 , ])

# getting third row
print(mat[2:, ])
print("\n")

# getting 1st and 3rd row
print(mat[::2, ])
print("\n == column == \n")

## ================== Column ============== 
# get first col
print(mat[: , :1:])

# getting third col
print(mat[: , 2::])
print("\n")

# getting 1st and 3rd row
print(mat[: , ::2])
print("\n")



[[1 2 3]
 [4 5 6]
 [7 8 9]]

 == Row == 

[[1 2 3]]
[[7 8 9]]


[[1 2 3]
 [7 8 9]]

 == column == 

[[1]
 [4]
 [7]]
[[3]
 [6]
 [9]]


[[1 3]
 [4 6]
 [7 9]]




In [ ]:

## ================== Get a row and column portion ============== 

print(mat[:: , :2:])

print("\n")
print(mat[:2: , :2:])

[[1 2]
 [4 5]
 [7 8]]


[[1 2]
 [4 5]]


## copy array

In [ ]:
# if not copy its changes the pointer value
print(arr1)

arr_mod = arr1[1:4]
print(arr_mod)

arr1[3] = 500
print(arr1)
print(arr_mod)


[  1   2 500   4]
[  2 500   4]
[  1   2 500 500]
[  2 500 500]


In [ ]:
print(arr1)

arr_mod = arr1[1:4].copy()
print(arr_mod)

arr1[1] = 20
print(arr1)
print(arr_mod)


[  1   2 500   2]
[  2 500   2]
[  1  20 500   2]
[  2 500   2]


## Advanced Indexing

In [ ]:
arr = np.array([10, 50, 40, 60])
print(arr[[0, 1, 3]])


print(arr2)
print(arr2[[0,1], [1, 2]])

[10 50 60]
[[1 2 3]
 [4 5 6]]
[2 6]


In [ ]:
# bolean 
print(arr[arr >= 50])

# all zero if logic match
arr[arr > 50] = 0
print(arr)

[50 60]
[10 50 40  0]


## Iteration

In [ ]:
# we can iterate any dimantion of array
for val in np.nditer(arr):
    print(val)

print()
# 2d array

for val in np.nditer(arr2):
    print(val)

10
50
40
0

1
2
3
4
5
6


In [ ]:
arr =np.array([1,2,3,4,5])
arr[1:4] = 0
print(arr)

[1 0 0 0 5]


## Practice Problems

### 1. You have a list of temperatures recorded in Celsius. Your task is to:
    - Create a NumPy array from the given list.
    - Convert all temperatures from Celsius to Fahrenheit. The formula is F = C* 1.8 + 32.
    - Print the new Fahrenheit array.


In [ ]:
temp = [15, 17, 20, 23, 25, 27, 29, 26, 22, 19]

temp_array = np.array(temp)
far_array = temp_array * 1.8 + 32
print(far_array)

[59.  62.6 68.  73.4 77.  80.6 84.2 78.8 71.6 66.2]


### 2.  You have a Python list containing the lap times (in seconds) for an athlete.
    - Convert the list into a NumPy array.
    - Print the array's shape, size, and data type.
    - The athlete wants to see their times in minutes. Create a new array by dividing all the lap times by 60.
    - Print the new array of lap times in minutes.


In [ ]:
lap_times = [72.5, 70.8, 69.9, 71.2, 70.3, 69.7, 68.9, 70.1]

lap_times_arr = np.array(lap_times)
print(lap_times_arr.shape)
print(lap_times_arr.size)
print(lap_times_arr.dtype)

lap_times_min = lap_times_arr / 60
print(lap_times_min)

(8,)
8
float64
[1.20833333 1.18       1.165      1.18666667 1.17166667 1.16166667
 1.14833333 1.16833333]
