## Numpy array manipulation

In [16]:
import numpy as np

In [17]:
arr1 = np.random.randint(1, 10, size=(3, 4))
arr2 = np.random.randint(12, 24, size=(3, 4))

print(arr1)
print(arr2)

[[1 4 6 8]
 [1 1 4 4]
 [4 1 2 1]]
[[13 23 18 22]
 [17 14 18 21]
 [22 15 14 13]]


In [18]:
a = arr1.reshape(1, 12)
print(a)

b = arr2.flatten()
print(b)

[[1 4 6 8 1 1 4 4 4 1 2 1]]
[13 23 18 22 17 14 18 21 22 15 14 13]


In [19]:
# column wise reshape
col_shape = np.ravel(arr1, order='F')
print(col_shape)

# column wise reshape
row_shape = np.ravel(arr1, order='C')
print(row_shape)

[1 1 4 4 1 1 6 4 2 8 4 1]
[1 4 6 8 1 1 4 4 4 1 2 1]


## Concate

In [20]:
arr1 = np.random.randint(1, 10, size=(3, 4))
arr2 = np.random.randint(12, 24, size=(3, 4))
print(arr1)
print(arr2)

[[6 3 4 2]
 [8 9 8 8]
 [1 2 9 6]]
[[21 19 20 12]
 [13 15 23 18]
 [14 23 16 12]]


In [21]:
x = np.concat((arr1, arr2), axis = 0) # row wise
print(x)

y = np.concat((arr1, arr2), axis = 1) # row wise
print(y)


[[ 6  3  4  2]
 [ 8  9  8  8]
 [ 1  2  9  6]
 [21 19 20 12]
 [13 15 23 18]
 [14 23 16 12]]
[[ 6  3  4  2 21 19 20 12]
 [ 8  9  8  8 13 15 23 18]
 [ 1  2  9  6 14 23 16 12]]


In [22]:
# error because :
# row wise concate korte hobe column same hobe
# column wise concate korle row same hote hobe

arr3 = np.random.randint(40, 50, size=(1, 2))
# z = np.concat((arr1, arr3), axis=0)
# print(z)


In [23]:
arr4 = np.random.randint(40, 50, size=(1, 4))
print(arr1.shape, arr4.shape)
z = np.concat((arr1, arr4), axis=0)
print(z)

# but can't concate column wise because row are not same

(3, 4) (1, 4)
[[ 6  3  4  2]
 [ 8  9  8  8]
 [ 1  2  9  6]
 [43 47 41 43]]


In [24]:
# Transpose matrix

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

x = np.array([a, b])

tanspose_mat = x.T
print(tanspose_mat)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [25]:
# Splite array without equel division

a = np.random.randint(1, 10, size=(10))
splited_arr = np.array_split(a, 5)
print(a)

print(splited_arr)

splited_arr = np.array_split(a, 3)
print(splited_arr)

# perfect splite when need equel division and must be divided
splited_arr = np.split(a, 2)
print(splited_arr)

# error
splited_arr = np.split(a, 4)
print(splited_arr)

[8 4 6 3 1 8 3 2 8 4]
[array([8, 4]), array([6, 3]), array([1, 8]), array([3, 2]), array([8, 4])]
[array([8, 4, 6, 3]), array([1, 8, 3]), array([2, 8, 4])]
[array([8, 4, 6, 3, 1]), array([8, 3, 2, 8, 4])]


ValueError: array split does not result in an equal division

## Arithmatical operation and Mathematical function

In [ ]:
x = np.array([10, 20, 30, 100])
y = np.array([20, 40, 50, 100])


# addition
print(x + y)
print(np.add(x,y))

# subtract
print(y - x)
print(np.subtract(x,y))


# multiply
print(y * x)
print(np.multiply(x,y))

# modolus
print(y % x)
print(np.mod(x,y))


In [ ]:
# Trigonomiti
z = np.array([5, 30, 90, 100])

# z is rediant
print(np.sin(z))

# degre to rediant
rad = np.deg2rad(z)
print(rad)

print(np.sin(rad))


# cos
print(np.cos(rad))

In [ ]:
# log
print(np.log10(z))

x = np.array([5, 128, 90, 100])
print(np.log2(x))

In [ ]:
print(np.cumulative_sum(x))

print(np.cumulative_prod(x))

print(np.lcm(x, y))
print(np.gcd(x, y))


In [ ]:
# brodcasting
z = np.array([5, 30, 90, 100])
print(z ** 2)  # broadcasting

print(z + 2)  # broadcasting

arr1 = np.random.randint(1, 10, size=(3, 4))
ans = z + arr1
print(ans)

# error
arr1 = np.random.randint(1, 10, size=(3, 3))
ans = z + arr1
print(ans)

# column size should be same


## Logical operator

In [ ]:
greater = z > 50
print(greater)

eq = z >= 90
print(eq)

print(x)
print(z)
print(x > z)

print(np.all(x > 1)) # check all are true


print(np.any(z >= 100)) # check all are true


print(np.any(z < 0)) # check all are true

## Sorting

In [ ]:
# inplace sorting

x = np.array([10, 2, 5, 9, 50])

z = x.copy()
print(z)
z.sort()
print(z)

In [ ]:
# copy sort
sorted_arra = np.sort(x)
print(sorted_arra)
print(x)

In [ ]:
# 2d array sort
x = np.array([[10, 2, 5], [5, 6, 7]])
print(x)

# axis 0 = vertical sort
# axis 1 = horizontal sort
print(np.sort(x, axis=0))
print(np.sort(x, axis=1))


## Searching 

In [ ]:
x = np.array([10, 2, 5, 9, 50])

# indexes of searching
idx = np.where(x >= 10)
print(idx)

# search and replace
idx = np.where(x >= 10, x,-1)
print(idx)

In [ ]:
# for 2d array searching 
x = np.array([[10, 2, 5], [5, 6, 7]])
idx = np.where(x > 5)
print(idx)

# (array([0, 1, 1]), array([0, 1, 2]))
#    (rows), (col) like x[0][0] > 5
idx = np.where(x > 5)
print(idx)

In [ ]:
# max min index
# result first occurence
x = np.array([10, 2, 5, 9, 50])
max_ids = np.argmax(x)
print(max_ids)

y = np.array([[10, 2, 5], [5, 6, 700]])
max_ids = np.argmax(y)
print(max_ids)


# max min index
# result first occurence
x = np.array([10, 2, 5, 9, 50])
min_ids = np.argmin(x)
print(min_ids)

y = np.array([[10, 2, 5], [5, 0, 700]])
min_ids = np.argmin(y)
print(min_ids)

In [ ]:
x = np.random.randint(1, 100, size=(100))
x

In [ ]:
print(np.count_nonzero(x > 50))
print(np.count_nonzero(x > 80))

In [ ]:
y = np.array([[10, 2, 50], [5, 60, 70]])
y

In [ ]:
print(np.count_nonzero(y > 10))
print(np.count_nonzero(y > 10, axis=1, keepdims=True)) # row wise
print(np.count_nonzero(y > 10, axis=0, keepdims=True)) # col wise

In [ ]:
print(np.unique(x))
print(np.unique(x, return_counts=True))
print(np.unique(x, return_index=True))



In [ ]:
y = np.array([[10, 2, 2], [5, 60, 70]])
print(y)

print(np.unique(y))
print(np.unique(y, axis=0)) # row wise
print(np.unique(y, axis=1)) # col wise

## Statistics fucntion

In [27]:
# load data
data = np.genfromtxt('student_scores.csv', delimiter=',', skip_header=1)
data

array([[78., 85., 82.],
       [56., 67., 72.],
       [89., 92., 88.],
       [45., 52., 58.],
       [70., 75., 80.],
       [92., 90., 91.],
       [61., 60., 62.],
       [55., 57., 54.],
       [88., 89., 87.],
       [74., 70., 76.],
       [66., 69., 68.],
       [80., 82., 81.],
       [59., 64., 60.],
       [73., 78., 74.],
       [91., 93., 90.],
       [68., 71., 69.],
       [77., 79., 78.],
       [84., 86., 85.],
       [62., 63., 65.],
       [95., 97., 96.]])

In [28]:
# statistics fucntion

math_data = data[::, :1:]
print(math_data.T)

max_marks = np.max(math_data)
print(f"max mark: {max_marks}")

min_marks = np.min(math_data)
print(f"min mark: {min_marks}")

avg_marks = np.average(math_data)
print(f"average mark: {avg_marks}, {np.mean(math_data)}")

median_math_marks = np.median(math_data)
print(f"median mark: {median_math_marks}") 

std_marks = np.std(math_data)
print(f"standart mark: {std_marks}")

# for i in math_data.astype(np.int64).flatten():
#     print(i)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
max mark: 95.0
min mark: 45.0
average mark: 73.15, 73.15
median mark: 73.5
standart mark: 13.788672887555204


In [ ]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 90])

data = np.array([study_hours, exam_scores])

correlation = np.corrcoef(data)

print("Correlation Matrix:\n", correlation)

Correlation Matrix:
 [[1.        0.9953792]
 [0.9953792 1.       ]]


## linear algebra

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

dot_product = np.dot(A, B)
print(dot_product)

[[ 58  64]
 [139 154]]


In [ ]:
# diagonal value sum/Trace
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [9, 4, 10],
]) 
# 1 + 5 + 10
print(np.trace(A))
print(np.diagonal(A)) # primary diagonal

print(np.flipud(A).diagonal()) # 2nd diagonal

16
[ 1  5 10]
[9 5 3]


In [ ]:
# determinate
det_A = np.linalg.det(A)
print(det_A)

# rank
rank_A = np.linalg.matrix_rank(A)
print(rank_A)

print(np.linalg.matrix_transpose(A))

mode = 'col'
axis = lambda st: 1 if st == 'row' else 0
print(axis)

-33.0
3
[[ 1  4  9]
 [ 2  5  4]
 [ 3  6 10]]
<function <lambda> at 0x177b16980>


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))

[[19 22]
 [43 50]]


## Practice problems

#### 1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.

In [ ]:
arr1 = np.array([1, 2, 3])
arra2 = np.array([
                    [1, 2, 3],
                    [4, 5, 6]
                ])

arr3 = np.array([
                    [
                        [1, 2, 3],
                        [4, 5, 6],
                    ],
                    [
                        [1, 2, 3],
                        [4, 5, 6]
                    ],
                    [
                        [1, 2, 3],
                        [4, 5, 6]
                    ],
])
    
print(arr1.ndim, arr1.shape)
print(arr2.ndim, arr2.shape)
print(arr3.ndim, arr3.shape)
print(arr3)

1 (3,)
2 (3, 4)
3 (3, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
