In [3]:
import torch

In [4]:
data = torch.tensor(
    [
        [1, 5, 6],
        [8, 8, 6],
        [1, 2 , 4]
    ]
)
data

tensor([[1, 5, 6],
        [8, 8, 6],
        [1, 2, 4]])

In [57]:
# tensor[row_start:row_end , col_start:col_end]
X = data[:,0:2].float()
y = data[:,2].float()
X, y

(tensor([[1., 5.],
         [8., 8.],
         [1., 2.]]),
 tensor([6., 6., 4.]))

In [58]:
def initialize_parameters(layer_dims):
    torch.manual_seed(3)
    parameters = {}
    L = len(layer_dims)

    for l in range(1, L):
      parameters['W' + str(l)] = torch.ones((layer_dims[l - 1], layer_dims[l])) * 0.1
      parameters['b' + str(l)] = torch.zeros((layer_dims[l], 1))

    return parameters

In [59]:
initialize_parameters( [2,2,1] )

{'W1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.],
         [0.]]),
 'W2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.]])}

In [60]:
def linear_forward( A_prev, W, b):
  Z = torch.matmul(W.T, A_prev) + b
  return Z

In [67]:
def L_layer_forward(X, parameters):
  A = X
  L = len(parameters) // 2

  for l in range(1, L + 1):
    A_prev = A
    wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    A = linear_forward(A_prev, wl, bl)

  return A, A_prev

In [71]:
params = initialize_parameters([2,2,1])
X_sample = X[0].reshape(2,1)
y_hat, A1 = L_layer_forward(X_sample,params)
y_hat, A1

(tensor([[0.1200]]),
 tensor([[0.6000],
         [0.6000]]))

In [85]:
def update_parameters(parameters, y, y_hat, A1, X, lr=0.001):

    err_signal = 2 * (y - y_hat)

     #  Save OLD W2 values before updating
    W2_00_old = parameters['W2'][0, 0].item()
    W2_10_old = parameters['W2'][1, 0].item()

    # Update Layer 2


    parameters['W2'][0, 0] += lr * err_signal * A1[0, 0]
    parameters['W2'][1, 0] += lr * err_signal * A1[1, 0]
    parameters['b2'][0, 0] += lr * err_signal #


    parameters['W1'][0, 0] += lr * err_signal * parameters['W2'][0, 0] * X[0, 0]
    parameters['W1'][0, 1] += lr * err_signal * parameters['W2'][0, 0] * X[1, 0]
    parameters['b1'][0, 0] += lr * err_signal * parameters['W2'][0, 0]

    parameters['W1'][1, 0] += lr * err_signal * parameters['W2'][1, 0] * X[0, 0]
    parameters['W1'][1, 1] += lr * err_signal * parameters['W2'][1, 0] * X[1, 0]
    parameters['b1'][1, 0] += lr * err_signal * parameters['W2'][1, 0]

    return parameters

Using loop

In [92]:
# using loop



params = initialize_parameters([2, 2, 1])
epochs = 10

for i in range(epochs):
    epoch_loss = 0
    for j in range(X.shape[0]):
        # Prepare sample
        X_sample = X[j].reshape(2, 1)
        y_sample = y[j]

        # Forward
        y_hat, A1 = L_layer_forward(X_sample, params)
        y_hat_scalar = y_hat[0, 0]

        # Update
        params = update_parameters(params, y_sample, y_hat_scalar, A1, X_sample)

        # Loss calculation
        loss = (y_sample - y_hat_scalar) ** 2
        epoch_loss += loss.item()

    print(f"Epoch - {i+1} Loss - {epoch_loss / X.shape[0]}")

Epoch - 1 Loss - 27.142158190409344
Epoch - 2 Loss - 25.835887908935547
Epoch - 3 Loss - 24.18109353383382
Epoch - 4 Loss - 22.114604949951172
Epoch - 5 Loss - 19.62799135843913
Epoch - 6 Loss - 16.815801938374836
Epoch - 7 Loss - 13.90416685740153
Epoch - 8 Loss - 11.213206926981607
Epoch - 9 Loss - 9.037955721219381
Epoch - 10 Loss - 7.51653524239858
